spring.application.name=user-service
 
server.port=${SERVER_PORT:8060}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/invoice_ms}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Root@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ------------------------------
# Actuator Configuration
# ------------------------------
management.endpoints.web.exposure.include=info,health
management.endpoint.info.enabled=true
management.info.env.enabled=true
 
# For production, this secret should be externalized (e.g., using environment variables).
# This is a 256-bit (32-byte) Base64 encoded secret suitable for HS256.
jwt.secret=bXktc3VwZXItc2VjdXJlLWFuZC1sb25nLXNlY3JldC1rZXktZm9yLXVzZXItc2VydmljZQ==
